### ISSUE TITLE
Problem with pseudo flat-field correction

### ISSUE THREAD

**Issue by jwrth** [biovoxxel/BioVoxxel-Toolbox#1]
Dear BioVoxxel-Team,

I am using your pseudo flat-field correction since longer and never had problems with it. Today I suddenly got following result when doing it:
![Screenshot 2022-11-11 101509](https://user-images.githubusercontent.com/76480183/201308822-508cea64-c436-4723-9dbd-2ccbc811b3e9.png)

The image turns completely black and looks almost like a mask. Do you have any idea what causes this effect?

I recently upgraded my computer to Windows 11. Could this cause the problem? I reinstalled Fiji and Biovoxxel but this also did not help. Thanks a lot in advance for your help!

**Comment by jwrth** [comment]
I found now that the problem is the 16-bit format of my images. When I convert it to 8-bit it works as usual. But I think I used the tool before also on 16-bit images. Did something change there in recent updates?

**Comment by biovoxxel** [comment]
Hm, strange. I tries it on a 16-bit image and for me it actually works! 

No, there was no change in the software recently. However, it could be related to the bit-depth.

You can also give the new [Pseudo-flatfield correction](https://biovoxxel.github.io/bv3dbox/#püseudo-flat-field-correction) from the [BioVoxxel 3D Box](https://biovoxxel.github.io/bv3dbox/) a try. Works the same and I would guess, that it does not create such issue.
To be able to use that follow the [installation instructions](https://biovoxxel.github.io/bv3dbox/#installation)

**Comment by jwrth** [comment]
Thanks a lot for the quick reply! Indeed, the correction in the BioVoxxel 3D Box works well and does not show this weird behaviour with 16-bit images. But one thing I realized is that the resulting image is 32-bit. Is there a reason for this or is this just a little bug?  Thanks again for your help!

**Comment by biovoxxel** [comment]
The 32-bit output is on purpose. Since the flat-field correction includes a division operation. The 32-bit image enables a more accurate result due to floating point numbers. So, it's a feature not a bug 🙂
