### ISSUE TITLE
Threshold Check Issues

### ISSUE THREAD

**Issue by cannons91** [biovoxxel/BioVoxxel-Toolbox#2]
Whenever I try to run threshold check from the BioVoxxel toolbox, it never seems to finish. I never get to the screen where it shows the 26 different threshold options. I don’t get an error either, it just simply says “Thresholding…” on and on. It worked one time, but not before or after that. Does this have something to do with the size of the image? There are 4 tiles of 20x, Z stack images. Is there a way to check thresholding progress to see if it really is just taking a very very long time?

**Comment by biovoxxel** [comment]
The original ThresholdCheck is not designed for 3D images.

I would recommend you to install the BioVoxxel 3D Box https://biovoxxel.github.io/bv3dbox/
